#pragma once

#include_next <mcuconf.h>

//I2C COMMUNICATION FOR OLED DISPLAY
#undef STM32_I2C_USE_I2C1
#define STM32_I2C_USE_I2C1 TRUE

//FULL DUPLEX COMMUNICATION THROUGH SERIAL
#undef STM32_SERIAL_USE_USART2
#define STM32_SERIAL_USE_USART2 TRUE

// TIMER FOR PWM DRIVER
#undef STM32_PWM_USE_TIM1
#undef STM32_PWM_USE_TIM2
#define STM32_PWM_USE_TIM1 TRUE
#define STM32_PWM_USE_TIM2 FALSE

#undef STM32_SERIAL_USART2_PRIORITY
#define STM32_SERIAL_USART2_PRIORITY 10

// 8 MHz CRYSTAL STM32 BOARD
#ifdef CRYSTAL_8MHZ
#    undef STM32_PLLM_VALUE
#    undef STM32_PLLN_VALUE
#    undef STM32_PLLP_VALUE
#    undef STM32_PLLQ_VALUE
#    undef STM32_PPRE1
#    undef STM32_PPRE2

#    define STM32_PLLM_VALUE 4
#    define STM32_PLLN_VALUE 168
#    define STM32_PLLP_VALUE 4
#    define STM32_PLLQ_VALUE 7
#    define STM32_PPRE1 STM32_PPRE1_DIV2
#    define STM32_PPRE2 STM32_PPRE2_DIV1
#endif