#pragma once

#include_next <mcuconf.h>

#undef STM32_I2C_USE_I2C1
#define STM32_I2C_USE_I2C1 TRUE

#undef STM32_SERIAL_USE_USART2
#define STM32_SERIAL_USE_USART2 TRUE

#undef STM32_PWM_USE_TIM1
#undef STM32_PWM_USE_TIM2
#define STM32_PWM_USE_TIM1 TRUE
#define STM32_PWM_USE_TIM2 FALSE

//#undef STM32_PWM_USE_ADVANCED
//#define STM32_PWM_USE_ADVANCED TRUE

#undef STM32_SERIAL_USART2_PRIORITY
#define STM32_SERIAL_USART2_PRIORITY 10